apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name vault-user
  namespace: vault
  labels:
    app: *name
spec:
  replicas: 1
  selector:
    matchLabels:
      name: *name
  template:
    metadata:
      labels:
        name: *name
    spec:
      containers:
        - name: *name
          image: vault:1.4.2
          env:
            - name: VAULT_ADDR
              value: "http://testvault.silkrode.com.tw"
          command: ["sleep"]
          args: ["infinite"]
