version: '3'

networks:

  subnet_1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24

services:

  vault_1:
    image: "hashicorp/vault:1.17.3"
    hostname: "vault_1"
    networks:
      subnet_1:
        ipv4_address: 172.16.238.21
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    ports:
      - "8200:8200"
    volumes:
      - ./vault:/vault
    entrypoint: vault server -dev

  mariadb_1:
    image: "mariadb:11.5.2"
    hostname: "mariadb_1"
    networks:
      subnet_1:
        ipv4_address: 172.16.238.22
    environment:
      - MARIADB_ROOT_PASSWORD=root
      # create a database and user for vault
      - MARIADB_USER=vault
      - MARIADB_PASSWORD=vault
      - MARIADB_DATABASE=vault
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/mariadb
