version: '3'

networks:
  subnet_1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24

services:

  consul_1:
    image: "hashicorp/consul:1.16.1"
    hostname: "consul_1"
    command: "agent -dev -client 0.0.0.0 -log-level=info"
    networks:
      subnet_1:
        ipv4_address: 172.16.238.10    
    ports:
      - "8301:8300"
      - "8401:8400"
      - "8501:8500"
      - "8601:8600"
      - "9001:9001"
    environment:
      - CONSUL_OPTS=-bootstrap-expect=3

  consul_2:
    image: "hashicorp/consul:1.16.1"
    hostname: "consul_2"
    command: "agent -dev -client 0.0.0.0 -log-level=info"
    networks:
      subnet_1:
        ipv4_address: 172.16.238.11
    ports:
      - "8302:8300"
      - "8402:8400"
      - "8502:8500"
      - "8602:8600"
      - "9002:9001"
    environment:
      - CONSUL_OPTS=-join 172.16.238.10
  
  consul_3:
    image: "hashicorp/consul:1.16.1"
    hostname: "consul_3"
    command: "agent -dev -client 0.0.0.0 -log-level=info"
    networks:
      subnet_1:
        ipv4_address: 172.16.238.12
    ports:
      - "8303:8300"
      - "8403:8400"
      - "8503:8500"
      - "8603:8600"
      - "9003:9001"
    environment:
      - CONSUL_OPTS=-join 172.16.238.10

  vault_1:
    depends_on:
      - consul_1
      - consul_2
      - consul_3
    image: "hashicorp/vault:1.17.1"
    hostname: "vault_1"
    networks:
      subnet_1:
        ipv4_address: 172.16.238.21
    environment:
      VAULT_API_ADDR: http://172.16.238.21:8200
      VAULT_CLUSTER_ADDR: https://172.16.238.21:8200
    ports:
      - "8201:8200"
    volumes:
      - ./config:/config
      #- ./config/vault/policies:/policies
    entrypoint: vault server -config=/config/vault.hcl

  vault_2:
    depends_on:
      - consul_1
      - consul_2
      - consul_3
    image: "hashicorp/vault:1.17.1"
    hostname: "vault_2"
    networks:
      subnet_1:
        ipv4_address: 172.16.238.22
    environment:
      VAULT_API_ADDR: http://172.16.238.22:8200
      VAULT_CLUSTER_ADDR: https://172.16.238.22:8200
    ports:
      - "8202:8200"
    volumes:
      - ./config:/config
      #- ./config/vault/policies:/policies
    entrypoint: vault server -config=/config/vault.hcl

  vault_3:
    depends_on:
      - consul_1
      - consul_2
      - consul_3
    image: "hashicorp/vault:1.17.1"
    hostname: "vault_3"
    networks:
      subnet_1:
        ipv4_address: 172.16.238.23
    environment:
      VAULT_API_ADDR: http://172.16.238.23:8200
      VAULT_CLUSTER_ADDR: https://172.16.238.23:8200
    ports:
      - "8203:8200"
    volumes:
      - ./config:/config
      #- ./config/vault/policies:/policies
    entrypoint: vault server -config=/config/vault.hcl
