apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: vault-server-ingress
  namespace: vault
  annotations:
    kubernetes.io/ingress.class: traefik
    # https://docs.traefik.io/routing/providers/kubernetes-ingress/
    traefik.ingress.kubernetes.io/router.tls: "true"
    #kubernetes.io/ingress.class: nginx
    #nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    #nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  # https://docs.traefik.io/v1.7/user-guide/kubernetes/#add-a-tls-certificate-to-the-ingress
  tls:
  - secretName: chechia-in-tls
    hosts:
      - vault.chechia.in
  - secretName: gcp-chechia-com-tw-tls
    hosts:
      - vault.gcp.chechia.net
  rules:
  - host: vault.chechia.in
    http:
      paths:
      - path: /ui
        backend:
          serviceName: vault-ui
          servicePort: 8200
      - path: /
        backend:
          serviceName: vault
          servicePort: 8200
  - host: vault.gcp.chechia.net
    http:
      paths:
      - path: /
        backend:
          serviceName: vault
          servicePort: 8200
