# A vault client deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name vault-user
  namespace: chechia
  labels:
    app: *name
spec:
  replicas: 1
  selector:
    matchLabels:
      name: *name
  template:
    metadata:
      labels:
        name: *name
    spec:
      serviceAccountName: chechia
      automountServiceAccountToken: true
      containers:
        - name: *name
          image: vault:1.5.4
          env:
            - name: VAULT_ADDR
              value: "http://vault.vault.svc.cluster.local:8200"
          command: ["sleep"]
          args: ["36000"]
